### PR TITLE
Implement search strategy [#3]; fix searching for phrases [#8]; misc; v1.3.0 (4)

### PR DESCRIPTION
**Pull request by savanto**
### Search strategy [#3]
- Enable searching by strategy in the preferences
- Select which search strategy you want to use (strategies are retrieved from the DICT server on demand using `SHOW STRATEGIES`)

### Databases
- Select which database you want to use (databases are retrieved from the DICT server on demand using `SHOW DATABASES`)

### Misc
- Phrases are now handled correctly [#8]
- App size should be slightly smaller now

### CODE REVIEW

**Comment by Michahel** [comment]
I did the testing.
Lookup does not work. Testing done for the server dict.org and dict.bible.ru. Word for test: "man". I have been seeing the message "Looking up word ..." for a long time, but in the end nothing is found.
I go to the settings. 
Tap on "Databases to search". I see the message "Fetching databases from dict server ...". In the end, the list of databases does not appear.
I turn on the option "Use search strategy". Tap on the "Search strategy". I see the message "Fetching strategies from dict server ...", but in the end the list of strategies does not appear.

**Comment by savanto** [comment]
@Michahel I think I've found the problem, working on a fix.

**Comment by savanto** [comment]
This should be fixed now in [v1.3.1](https://github.com/savanto/AnDICT-Android/releases/tag/v1.3.1).

**Comment by Michahel** [comment]
It works OK

**Comment by Michahel** [comment]
Recently I faced a problem when using Word strategy and the lookup is for all databases.

**How to reproduce the problem**

Go to Settings.
Tap on the *DICT server address.*
Enter *dict.bible.ru* and tap on the OK button.
Tap on the *Databases to search.*
Select the "All matches" option and tap on the OK button.
Tap on the *Use search strategy* to enable it.
Tap on the *Search strategy.*
Select the "word: Match a word anywhere in the headword" option and tap on the OK button.

[See screen capture 1](https://1drv.ms/u/s!ApR0ksy-ixJUonUNHBZks_0nLDzn).

Exit from Settings.
Enter the word אדם to search for. {[See screen capture 2](https://1drv.ms/u/s!ApR0ksy-ixJUono7foQA67p8niH5)}
Tap on the "Lookup" button. "Looking up word..." message will appear. {[See screen capture 3](https://1drv.ms/u/s!ApR0ksy-ixJUon2JMi4i9xU5e3nz)}
Then, unexpectedly, the program window disappears and the following message appears: "AnDICT has stopped" {[See screen capture 4](https://1drv.ms/u/s!ApR0ksy-ixJUon8oFP2wj5En04Rh)}

**Pull request merged**
